import { run, pi } from "@ai-hero/sandcastle";
import { noSandbox } from "@ai-hero/sandcastle/sandboxes/no-sandbox";

await run({
  name: "issue-52",
  sandbox: noSandbox(),
  agent: pi("9router/high-context-coding"),
  prompt: "Implement GitHub issue #52: UI Redesign Map — NetZeroCarbon Platform\n\nIssue details:\n## Destination\n\nTransform the NetZeroCarbon POC from basic HTML into a polished, production-quality UI following the design system in `stitch_netzerocarbon_platform/DESIGN.md`. Apply claymorphism, glassmorphism, and neumorphism across all screens. Migrate frontend to Next.js with React.\n\n## Notes\n\n- Design system: `stitch_netzerocarbon_platform/netzerocarbon/DESIGN.md`\n- HTML prototypes: `stitch_netzerocarbon_platform/{screen}/code.html`\n- Screenshots: `stitch_netzerocarbon_platform/{screen}/screen.png`\n- Logo: `stitch_netzerocarbon_platform/netzerocarbon_logo/screen.png`\n- Avatar: `stitch_netzerocarbon_platform/professional_headshot_of_a_friendly_thai_male_farmer_in_his_40s_wearing_a_clean/screen.png`\n- Colors: Primary #06C755, Secondary #1A1A2E, Accent #FF6B35, Background #F0F4F8\n- Typography: Inter + Sarabun, 1.6 line-height\n- Elevation: 4-level (neumorphic → claymorphic → glassmorphic)\n- Mobile: 44px touch targets, Thai text\n- Frontend: Next.js 14+ (App Router) + React 18 + Tailwind CSS 3\n\n## Decisions so far\n\n## Not yet specified\n\n- Season summary form LIFF\n- Photo upload LIFF with camera\n- Admin detail panel with GPS map\n- Sponsor live counter animation\n- Responsive breakpoints\n- Next.js deployment strategy (Vercel vs Cloudflare Pages)\n\n## Out of scope\n\n- Voice/STT (phase 2)\n- Rich Menu (YAGNI)\n- Multi-language (Thai only)\n\n## Tickets\n\n- [ ] #58 — Migrate Frontend to Next.js (START HERE)\n- [ ] #53 — LIFF Chat Interface (Claymorphic Design)\n- [ ] #54 — Photo Upload LIFF (Camera Interface)\n- [ ] #55 — Season Summary Form LIFF\n- [ ] #56 — Admin Review Dashboard (Design System)\n- [ ] #57 — Sponsor Dashboard (Design System)\n\nInstructions:\n1. Read and understand the issue requirements\n2. Implement the changes in the codebase\n3. Write or update tests if applicable\n4. Run typecheck and tests to verify your changes work\n5. Commit your changes with a message starting with #52:\n6. Make sure all tests pass before finishing\n\nFocus on making the minimal correct changes to satisfy the issue requirements.\n",
  maxIterations: 1,
  branchStrategy: { type: "merge-to-head" },
});
