/**
 * Issue #50 — Demo seed script for field testing.
 * Seeds specific demo data for the field test script.
 * Run: bun run demo/seed-demo.ts
 */

const DEMO_FARMERS = [
  {
    id: "demo-farmer-1",
    full_name: "สมชาย ใจดี",
    phone: "0812345678",
    gender: "male",
    addr_province: "เชียงใหม่",
    addr_district: "แม่ริม",
    addr_subdistrict: "บ้านปง",
    addr_village: "หมู่ 4",
  },
  {
    id: "demo-farmer-2",
    full_name: "สมหญิง รักโลก",
    phone: "0823456789",
    gender: "female",
    addr_province: "เชียงใหม่",
    addr_district: "สันทราย",
    addr_subdistrict: "สันทรายหลวง",
    addr_village: "หมู่ 2",
  },
];

const DEMO_PLOTS = [
  {
    id: "demo-plot-1",
    farmer_id: "demo-farmer-1",
    plot_code: "P-DMO-001",
    deed_no: "12345",
    doc_type: "chanote",
    tenure: "owner",
    area_rai: 20,
    centroid_lat: 18.7883,
    centroid_lng: 98.9853,
  },
  {
    id: "demo-plot-2",
    farmer_id: "demo-farmer-2",
    plot_code: "P-DMO-002",
    deed_no: "67890",
    doc_type: "ns3k",
    tenure: "tenant",
    area_rai: 12,
    centroid_lat: 18.8123,
    centroid_lng: 99.0123,
  },
];

const DEMO_USERS = [
  {
    id: "demo-admin",
    email: "admin@test.com",
    password_hash: "placeholder-hash",
    role: "admin",
    name: "Admin Demo",
  },
  {
    id: "demo-sponsor",
    email: "sponsor@test.com",
    password_hash: "placeholder-hash",
    role: "sponsor",
    name: "Sponsor Demo",
  },
];

function buildInsertSQL(table: string, cols: string[]): string {
  const placeholders = cols.map(() => "?").join(", ");
  return `INSERT OR IGNORE INTO ${table} (${cols.join(", ")}) VALUES (${placeholders})`;
}

function insertFarmers(): string[] {
  const cols = [
    "id", "full_name", "phone", "gender",
    "addr_province", "addr_district", "addr_subdistrict", "addr_village",
  ];
  const sql = buildInsertSQL("farmers", cols);
  return DEMO_FARMERS.map(
    (f) =>
      `${sql} -- ${f.id} | ${f.full_name} | ${f.phone}`,
  );
}

function insertPlots(): string[] {
  const cols = [
    "id", "farmer_id", "plot_code", "deed_no",
    "doc_type", "tenure", "area_rai", "centroid_lat", "centroid_lng",
  ];
  const sql = buildInsertSQL("plots", cols);
  return DEMO_PLOTS.map(
    (p) =>
      `${sql} -- ${p.id} | ${p.plot_code}`,
  );
}

function insertUsers(): string[] {
  const cols = ["id", "email", "password_hash", "role", "name"];
  const sql = buildInsertSQL("users", cols);
  return DEMO_USERS.map(
    (u) =>
      `${sql} -- ${u.id} | ${u.email}`,
  );
}

function buildSQLFile(): string {
  const lines = [
    "-- Demo seed data for field testing",
    "-- Generated by demo/seed-demo.ts",
    "",
  ];

  for (const sql of insertFarmers()) {
    lines.push(sql);
  }
  lines.push("");

  for (const sql of insertPlots()) {
    lines.push(sql);
  }
  lines.push("");

  for (const sql of insertUsers()) {
    lines.push(sql);
  }
  lines.push("");

  return lines.join("\n");
}

function printSummary(): void {
  console.log("=== NetZeroCarbon Demo Seed ===");
  console.log(`Farmers: ${DEMO_FARMERS.length}`);
  console.log(`Plots:   ${DEMO_PLOTS.length}`);
  console.log(`Users:   ${DEMO_USERS.length}`);
  console.log("");
  console.log("To apply this seed via wrangler:");
  console.log("  bunx wrangler d1 execute netzero --local --file=demo/seed-demo.sql");
  console.log("");
  console.log("Or use the generated SQL below:");
  console.log("─".repeat(50));
}

function main(): void {
  printSummary();
  const sql = buildSQLFile();
  console.log(sql);
}

// CLI entry
if (import.meta.main) {
  main();
}

export { DEMO_FARMERS, DEMO_PLOTS, DEMO_USERS, buildSQLFile };
